// ============================================================================
// SETUP DATA — Infrastructure data seeded during first-run setup
// Separated from seed.ts to allow the /api/setup route to seed without
// requiring command-line access (essential for Vercel deployment)
// ============================================================================

export const DEFAULT_SECTORS = [
  { name: 'Automobile (Spare Parts)', riskScore: 0.4, benchmarkedMargin: 22.5 },
  { name: 'Food & Beverage', riskScore: 0.5, benchmarkedMargin: 18.0 },
  { name: 'Fashion & Textiles', riskScore: 0.6, benchmarkedMargin: 28.0 },
  { name: 'Electronics / Gadgets', riskScore: 0.4, benchmarkedMargin: 15.0 },
  { name: 'Building Materials', riskScore: 0.3, benchmarkedMargin: 12.0 },
  { name: 'Pharmaceuticals', riskScore: 0.3, benchmarkedMargin: 20.0 },
  { name: 'General Merchandise', riskScore: 0.5, benchmarkedMargin: 18.0 },
  { name: 'Agriculture / Farming', riskScore: 0.7, benchmarkedMargin: 25.0 },
  { name: 'Services / Professional', riskScore: 0.4, benchmarkedMargin: 35.0 },
  { name: 'Transport & Logistics', riskScore: 0.6, benchmarkedMargin: 22.0 },
  { name: 'Sales of hair extension/accessories', riskScore: 0.5, benchmarkedMargin: 20.41 },
  { name: 'Cosmetics', riskScore: 0.5, benchmarkedMargin: 19.00 },
  { name: 'Sales of wood', riskScore: 0.4, benchmarkedMargin: 22.72 },
  { name: 'Sales of Phone accessories', riskScore: 0.4, benchmarkedMargin: 19.65 },
  { name: 'Sales of Tyres (General Auto)', riskScore: 0.4, benchmarkedMargin: 18.31 },
  { name: 'Sales of Trucks spare parts', riskScore: 0.4, benchmarkedMargin: 25.00 },
  { name: 'Sales Agro-allied products', riskScore: 0.6, benchmarkedMargin: 19.22 },
  { name: 'Sales of Baby Items', riskScore: 0.5, benchmarkedMargin: 18.00 },
  { name: 'Aluminium profiles and accessories', riskScore: 0.4, benchmarkedMargin: 14.62 },
  { name: 'Fabrication and sale of aluminium', riskScore: 0.4, benchmarkedMargin: 25.00 },
  { name: 'Sales of Suspended Ceiling', riskScore: 0.4, benchmarkedMargin: 15.90 },
  { name: 'Sales of POP', riskScore: 0.4, benchmarkedMargin: 22.36 },
  { name: 'Sales of Plank', riskScore: 0.4, benchmarkedMargin: 18.62 },
  { name: 'Sales of provision and groceries', riskScore: 0.5, benchmarkedMargin: 11.05 },
  { name: 'Sales of Auto-paints', riskScore: 0.4, benchmarkedMargin: 20.46 },
  { name: 'Sales of iPhone and accessories', riskScore: 0.4, benchmarkedMargin: 18.93 },
  { name: 'Sales of Pharmaceutical products', riskScore: 0.3, benchmarkedMargin: 22.62 },
  { name: 'Sales of Cellotape', riskScore: 0.5, benchmarkedMargin: 25.00 },
  { name: 'Sales of fabric and textile', riskScore: 0.6, benchmarkedMargin: 19.28 },
  { name: 'Sales of Palm Oil', riskScore: 0.6, benchmarkedMargin: 15.00 },
  { name: 'Sale of alcoholic drinks', riskScore: 0.5, benchmarkedMargin: 10.01 },
  { name: 'Sale of non-alcoholic drinks', riskScore: 0.5, benchmarkedMargin: 8.13 },
  { name: 'Sales of assorted wines', riskScore: 0.5, benchmarkedMargin: 20.44 },
  { name: 'Iron and steel rods', riskScore: 0.3, benchmarkedMargin: 11.35 },
  { name: 'Water production/beverage distribution', riskScore: 0.5, benchmarkedMargin: 25.00 },
  { name: 'Sales of footwears', riskScore: 0.6, benchmarkedMargin: 11.32 },
  { name: 'Haulage/Logistics', riskScore: 0.6, benchmarkedMargin: 77.89 },
  { name: 'Cooking Gas/home accessories', riskScore: 0.5, benchmarkedMargin: 11.00 },
  { name: 'Food chemicals', riskScore: 0.4, benchmarkedMargin: 7.19 },
  { name: 'Production of paints', riskScore: 0.4, benchmarkedMargin: 25.00 },
  { name: 'Production and sale of polythene', riskScore: 0.4, benchmarkedMargin: 25.00 },
  { name: 'Building materials (roofing)', riskScore: 0.3, benchmarkedMargin: 16.55 },
  { name: 'Hospital', riskScore: 0.3, benchmarkedMargin: 25.00 },
  { name: 'School laboratory equipment', riskScore: 0.4, benchmarkedMargin: 23.00 },
  { name: 'Automobile spare-parts', riskScore: 0.4, benchmarkedMargin: 25.00 },
  { name: 'Building block production/installation', riskScore: 0.3, benchmarkedMargin: 20.00 },
  { name: 'Bakery/Confectionaries', riskScore: 0.5, benchmarkedMargin: 15.00 },
  { name: 'Sale of PVC water pipes and fittings', riskScore: 0.4, benchmarkedMargin: 19.72 },
  { name: 'Sales of Mobile phones', riskScore: 0.4, benchmarkedMargin: 21.00 },
  { name: 'Butchers/sale of meat', riskScore: 0.5, benchmarkedMargin: 21.36 },
  { name: 'Welding Service (Metal/Tank)', riskScore: 0.4, benchmarkedMargin: 22.00 },
  { name: 'Electrical home accessories', riskScore: 0.4, benchmarkedMargin: 15.14 },
  { name: 'Printing Materials and printing services', riskScore: 0.4, benchmarkedMargin: 25.00 },
  { name: 'Sales of clothings and boutique', riskScore: 0.6, benchmarkedMargin: 15.61 },
  { name: 'Sale of industrial papers', riskScore: 0.4, benchmarkedMargin: 19.37 },
  { name: 'Sales of Alubond sheet', riskScore: 0.4, benchmarkedMargin: 21.35 },
  { name: 'General building materials', riskScore: 0.3, benchmarkedMargin: 18.55 },
  { name: 'Sales of cars', riskScore: 0.4, benchmarkedMargin: 22.76 },
  { name: 'Sales of Laminated Wood/HDF', riskScore: 0.4, benchmarkedMargin: 20.19 },
  { name: 'Sales of Metal Scrap', riskScore: 0.4, benchmarkedMargin: 22.31 },
  { name: 'Animal feeds', riskScore: 0.6, benchmarkedMargin: 10.19 },
  { name: 'Sales of Iron and building materials', riskScore: 0.3, benchmarkedMargin: 13.45 },
  { name: 'Sales of electronics and Computers', riskScore: 0.4, benchmarkedMargin: 17.29 },
  { name: 'Sales of Car engine', riskScore: 0.4, benchmarkedMargin: 16.96 },
  { name: 'Sales of Electronics', riskScore: 0.4, benchmarkedMargin: 20.13 },
  { name: 'Sales of frozen food', riskScore: 0.5, benchmarkedMargin: 10.70 },
  { name: 'Mattress and pillow', riskScore: 0.5, benchmarkedMargin: 14.87 },
  { name: 'Sales of electrical material', riskScore: 0.4, benchmarkedMargin: 24.00 },
  { name: 'Sales of PMS (Petroleum Product)', riskScore: 0.3, benchmarkedMargin: 9.78 },
  { name: 'Sales recharge cards', riskScore: 0.5, benchmarkedMargin: 7.99 },
  { name: 'Sales of rechargeable and storage', riskScore: 0.5, benchmarkedMargin: 18.53 },
  { name: 'Sales of truck head and spare parts', riskScore: 0.4, benchmarkedMargin: 14.00 },
  { name: 'Poultry farming/sale of eggs', riskScore: 0.6, benchmarkedMargin: 16.80 },
  { name: 'Sales of industrial electrical', riskScore: 0.4, benchmarkedMargin: 21.00 },
  { name: 'Fabrication and sale of furniture', riskScore: 0.4, benchmarkedMargin: 25.00 },
  { name: 'Sales of sesame seeds, cashew nuts', riskScore: 0.6, benchmarkedMargin: 12.69 },
  { name: 'Sales of foodstuffs (garri, rice)', riskScore: 0.5, benchmarkedMargin: 13.69 },
  { name: 'Sales of building doors (imported)', riskScore: 0.3, benchmarkedMargin: 22.35 },
  { name: 'General industrial chemicals', riskScore: 0.4, benchmarkedMargin: 22.65 },
  { name: 'Tailoring materials', riskScore: 0.6, benchmarkedMargin: 19.25 },
  { name: 'Hotel/hospitality', riskScore: 0.5, benchmarkedMargin: 77.89 },
  { name: 'Production of tissue paper/hand towel', riskScore: 0.4, benchmarkedMargin: 23.00 },
  { name: 'Ladies clothes', riskScore: 0.6, benchmarkedMargin: 18.00 },
  { name: 'Medical & scientific equipment', riskScore: 0.3, benchmarkedMargin: 22.62 },
  { name: 'Sales of bags', riskScore: 0.6, benchmarkedMargin: 21.95 },
  { name: 'Sales of furniture', riskScore: 0.4, benchmarkedMargin: 19.16 },
  { name: 'Production of furniture', riskScore: 0.4, benchmarkedMargin: 25.00 },
];

export const BRANCHES = [
  { name: 'Lagos Mainland (Ikeja)', code: 'LAG-01', state: 'Lagos', address: 'CMD Road, Ikeja GRA, Lagos', phoneContact: '+234 803 000 0001' },
  { name: 'Lagos Island', code: 'LAG-02', state: 'Lagos', address: 'Victoria Island, Lagos', phoneContact: '+234 803 000 0002' },
  { name: 'Abuja Central', code: 'ABJ-01', state: 'FCT', address: 'Wuse II, Abuja', phoneContact: '+234 803 000 0003' },
  { name: 'Abuja Garki', code: 'ABJ-02', state: 'FCT', address: 'Garki, Abuja', phoneContact: '+234 803 000 0004' },
  { name: 'Ibadan', code: 'IBD-01', state: 'Oyo', address: 'Ring Road, Ibadan', phoneContact: '+234 803 000 0005' },
  { name: 'Benin', code: 'BEN-01', state: 'Edo', address: 'Sapele Road, Benin City', phoneContact: '+234 803 000 0006' },
];

export const CHART_OF_ACCOUNTS = [
  { code: '1000', name: 'Cash on Hand', type: 'ASSET', subType: 'current_asset' },
  { code: '1010', name: 'Bank — Operations', type: 'ASSET', subType: 'current_asset' },
  { code: '1020', name: 'Bank — Disbursement', type: 'ASSET', subType: 'current_asset' },
  { code: '1100', name: 'Accounts Receivable', type: 'ASSET', subType: 'current_asset' },
  { code: '1200', name: 'Loans Receivable (Principal)', type: 'ASSET', subType: 'current_asset' },
  { code: '1210', name: 'Accrued Interest Income', type: 'ASSET', subType: 'current_asset' },
  { code: '1300', name: 'Prepaid Expenses', type: 'ASSET', subType: 'current_asset' },
  { code: '1500', name: 'Office Equipment', type: 'ASSET', subType: 'fixed_asset' },
  { code: '1510', name: 'Furniture & Fixtures', type: 'ASSET', subType: 'fixed_asset' },
  { code: '1520', name: 'Motor Vehicles', type: 'ASSET', subType: 'fixed_asset' },
  { code: '2000', name: 'Accounts Payable', type: 'LIABILITY', subType: 'current_liability' },
  { code: '2100', name: 'Customer Deposits', type: 'LIABILITY', subType: 'current_liability' },
  { code: '2200', name: 'Accrued Expenses', type: 'LIABILITY', subType: 'current_liability' },
  { code: '2300', name: 'Interest Payable', type: 'LIABILITY', subType: 'current_liability' },
  { code: '3000', name: 'Share Capital', type: 'EQUITY', subType: 'equity' },
  { code: '3100', name: 'Retained Earnings', type: 'EQUITY', subType: 'equity' },
  { code: '4000', name: 'Interest Income', type: 'REVENUE', subType: 'operating_revenue' },
  { code: '4100', name: 'Processing Fees', type: 'REVENUE', subType: 'operating_revenue' },
  { code: '4200', name: 'Upfront Fees', type: 'REVENUE', subType: 'operating_revenue' },
  { code: '4300', name: 'Late Payment Fees', type: 'REVENUE', subType: 'operating_revenue' },
  { code: '5000', name: 'Cost of Funds', type: 'EXPENSE', subType: 'operating_expense' },
  { code: '5100', name: 'Salaries & Wages', type: 'EXPENSE', subType: 'operating_expense' },
  { code: '5200', name: 'Rent', type: 'EXPENSE', subType: 'operating_expense' },
  { code: '5300', name: 'Utilities', type: 'EXPENSE', subType: 'operating_expense' },
  { code: '5400', name: 'Marketing', type: 'EXPENSE', subType: 'operating_expense' },
  { code: '5500', name: 'Bad Debt Expense', type: 'EXPENSE', subType: 'operating_expense' },
  { code: '5600', name: 'Depreciation', type: 'EXPENSE', subType: 'operating_expense' },
  { code: '5700', name: 'Audit & Legal', type: 'EXPENSE', subType: 'operating_expense' },
  { code: '5800', name: 'Bank Charges', type: 'EXPENSE', subType: 'operating_expense' },
  { code: '5900', name: 'Miscellaneous', type: 'EXPENSE', subType: 'operating_expense' },
];

export const LOAN_PRODUCTS = [
  { title: 'Micro Loan', description: 'Small working capital for micro businesses', minimumAmount: 50000, maximumAmount: 500000, interestRate: 5, minTenor: 1, maxTenor: 6 },
  { title: 'SME Loan', description: 'Business expansion for small businesses', minimumAmount: 500000, maximumAmount: 5000000, interestRate: 3.5, minTenor: 3, maxTenor: 12 },
  { title: 'SME Plus', description: 'Larger facility for established SMEs', minimumAmount: 5000000, maximumAmount: 20000000, interestRate: 2.5, minTenor: 6, maxTenor: 24 },
  { title: 'Exception', description: 'Special facilities above standard limits', minimumAmount: 20000000, maximumAmount: 50000000, interestRate: 2, minTenor: 6, maxTenor: 36 },
];
